const SHEETS_URL='https://script.google.com/macros/s/AKfycbyeCyjanS_CO_PuiYKQAFEU9RdWxntkRzNV60ZCH7MXt3HXb1trZjW9uk45U0kBZNeqnw/exec'; // ← isi URL /exec Anda
const SHEETS_KEY='sarpras2026';
const Sheets={available(){return typeof SHEETS_URL==='string'&&SHEETS_URL.includes('/exec');},
 async get(p){const r=await fetch(SHEETS_URL+'?'+new URLSearchParams({key:SHEETS_KEY,...p}));if(!r.ok)throw new Error('HTTP '+r.status);return r.json();},
 async post(p){const r=await fetch(SHEETS_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({key:SHEETS_KEY,...p})});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}};
let DATA={sekolah:[],sarpras:[],laporan:[]};
async function pull(){if(!Sheets.available())return false;try{syncBadge('🔄 Memuat...');const d=await Sheets.get({action:'getData'});if(!d.ok){syncBadge('❌ '+(d.msg||''),false);return false;}DATA.sekolah=d.sekolah||[];DATA.sarpras=d.sarpras||[];DATA.laporan=d.laporan||[];syncBadge('✅ '+DATA.sekolah.length+' sekolah · '+DATA.laporan.length+' laporan');return true;}catch(e){syncBadge('❌ '+e.message,false);return false;}}
function withSync(fn){if(Sheets.available())pull().finally(fn);else fn();}
async function pushMaster(){return await Sheets.post({action:'saveData',sekolah:DATA.sekolah,sarpras:DATA.sarpras});}
function syncBadge(t,ok=true){let el=document.getElementById('sync-badge');if(!el){el=document.createElement('div');el.id='sync-badge';el.style.cssText='position:fixed;bottom:14px;right:14px;z-index:999;padding:8px 14px;border-radius:999px;font-size:12px;font-weight:700;background:#fff;box-shadow:0 2px 10px rgba(0,0,0,.15);max-width:340px;';document.body.appendChild(el);}el.textContent=t;el.style.border=ok?'1px solid #16a34a':'1px solid #dc2626';el.style.color=ok?'#166534':'#991b1b';}
async function testKoneksi(){try{const d=await Sheets.get({action:'getData'});alert(d.ok?('✅ OK\nSekolah:'+d.sekolah.length+'\nSarpras:'+d.sarpras.length+'\nLaporan:'+d.laporan.length):('❌ '+d.msg));}catch(e){alert('❌ '+e.message);}}
function nextSeq(list,prefix,pad){let m=0;list.forEach(x=>{const mm=String(x.id||'').match(new RegExp('^'+prefix+'(\\d+)$'));if(mm)m=Math.max(m,parseInt(mm[1]));});return prefix+String(m+1).padStart(pad,'0');}
function today(){return new Date().toISOString().slice(0,10);}

const Auth={KEY:'sarpras_session',login(u){localStorage.setItem(this.KEY,JSON.stringify(u));},current(){try{return JSON.parse(localStorage.getItem(this.KEY));}catch(e){return null;}},logout(){localStorage.removeItem(this.KEY);location.href='login.html';},role(){const u=this.current();return u?u.role:null;}};
const LOCAL_USERS=[{id:1,username:'admin',password:'admin123',nama:'Administrator',role:'admin'},{id:2,username:'kepsek',password:'kepsek123',nama:'Kepala Sekolah',role:'kepsek'},{id:3,username:'pimpinan',password:'pin123',nama:'Kepala Dinas',role:'pimpinan'}];
async function doVerify(u,p){if(Sheets.available()){try{const r=await Sheets.post({action:'login',username:u,password:p,token:''});return r.ok?r.user:null;}catch(e){alert('Koneksi gagal: '+e.message);return null;}}const x=LOCAL_USERS.find(x=>x.username===u&&x.password===p);return x||null;}

const MENUS=[{key:'dashboard',label:'Dashboard',icon:'📊',file:'dashboard.html'},{key:'sekolah',label:'Data Sekolah',icon:'🏫',file:'sekolah.html'},{key:'sarpras',label:'Sarana Prasarana',icon:'🗄️',file:'sarpras.html'},{key:'laporan',label:'Laporan Kerusakan',icon:'📣',file:'laporan.html'},{key:'monitoring',label:'Monitoring',icon:'🛠️',file:'monitoring.html'},{key:'peta',label:'Peta Geospasial',icon:'🗺️',file:'peta.html'},{key:'pimpinan',label:'Dashboard Pimpinan',icon:'🏛️',file:'pimpinan.html'},{key:'users',label:'Manajemen User',icon:'👥',file:'users.html'}];
const ROLES={admin:{label:'Administrator',menus:['dashboard','sekolah','sarpras','laporan','monitoring','peta','pimpinan','users']},kepsek:{label:'Kepala Sekolah',menus:['dashboard','laporan','monitoring','peta']},pimpinan:{label:'Pimpinan',menus:['dashboard','monitoring','peta','pimpinan']}};
const PERMISSIONS={admin:['export','print','create','edit','delete'],kepsek:['export','print','create'],pimpinan:['export','print']};
function can(a){const u=Auth.current();return u&&(PERMISSIONS[u.role]||[]).includes(a);}
function requireAuth(k){const u=Auth.current();if(!u){location.href='login.html';return false;}if(!ROLES[u.role].menus.includes(k)){alert('⛔ Tidak ada akses.');location.href='dashboard.html';return false;}return true;}
function renderMenu(a){const role=Auth.role(),u=Auth.current();if(!role)return;let h=`<div class="user-box"><div class="user-avatar">${(u.nama||'U').charAt(0).toUpperCase()}</div><div><div class="user-name">${u.nama}</div><div class="user-role">${ROLES[role].label}</div></div></div><ul class="menu-list">`;MENUS.forEach(m=>{if(ROLES[role].menus.includes(m.key))h+=`<li><a href="${m.file}" class="${m.key===a?'active':''}"><span>${m.icon}</span> ${m.label}</a></li>`;});h+=`<li><a href="#" class="logout" onclick="Auth.logout();return false;"><span>🚪</span> Keluar</a></li></ul>`;document.getElementById('sidebar-menu').innerHTML=h;const hu=document.getElementById('header-username');if(hu)hu.textContent=u.nama+' ('+ROLES[role].label+')';}
function buildToolbar(id,o){const el=document.getElementById(id);el.innerHTML='';let h='';if(o.createLabel&&can('create'))h+=`<button class="btn btn-primary" id="${id}_add">${o.createLabel}</button>`;if(can('export'))h+=`<button class="btn btn-success" id="${id}_exp">⬇️ Export</button>`;if(can('print'))h+=`<button class="btn btn-info" id="${id}_pri">🖨️ Cetak</button>`;el.innerHTML=h;const A=document.getElementById(id+'_add'),E=document.getElementById(id+'_exp'),P=document.getElementById(id+'_pri');if(A&&o.onCreate)A.onclick=o.onCreate;if(E&&o.onExport)E.onclick=o.onExport;if(P&&o.onPrint)P.onclick=o.onPrint;}
function exportExcel(rows,name,sheet){if(!window.XLSX)return alert('Library Excel belum termuat.');if(!rows.length)return alert('Tidak ada data.');const ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheet||'Data');XLSX.writeFile(wb,name+'.xlsx');}
function printTable(t,hd,rows){const u=Auth.current();let b='<table border="1" cellspacing="0" cellpadding="5"><thead><tr>'+hd.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+hd.map(h=>`<td>${r[h]??''}</td>`).join('')+'</tr>').join('')+'</tbody></table>';const w=window.open('','_blank');w.document.write(`<!DOCTYPE html><html><head><title>${t}</title><style>body{font-family:Arial;padding:20px;}h2{margin:0 0 4px;}.meta{font-size:11px;color:#555;margin-bottom:14px;}table{border-collapse:collapse;width:100%;font-size:11px;}th{background:#16283f;color:#fff;}th,td{border:1px solid #333;padding:5px;text-align:left;}</style></head><body><h2>${t}</h2><div class="meta">SIGAP SARPRAS - SD BADUNG | ${u?u.nama:'-'} | ${new Date().toLocaleString('id-ID')}</div>${b}<script>window.onload=function(){window.print();}<\/script></body></html>`);w.document.close();}
function fileToBase64(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onerror=rej;fr.onload=e=>{const img=new Image();img.onload=()=>{const max=900;let w=img.width,h=img.height;const sc=Math.min(1,max/Math.max(w,h));w=Math.round(w*sc);h=Math.round(h*sc);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);res(c.toDataURL('image/jpeg',0.72).split(',')[1]);};img.onerror=rej;img.src=e.target.result;};fr.readAsDataURL(file);});}